"""
REST-like API descriptor for AI agents and LLM tool-use.

This module provides structured metadata about the dataset
so that AI agents (e.g., ChatGPT, Claude, Copilot) can
programmatically discover and use the dataset.

Usage by an AI agent:
    >>> from cylinderwake.api import DATASET_CARD
    >>> print(DATASET_CARD)  # structured dict with all metadata
"""

from __future__ import annotations

DATASET_CARD = {
    "name": "CylinderWake3900",
    "version": "1.0.0",
    "description": (
        "Lagrangian and Eulerian dataset of the wake downstream of a smooth "
        "cylinder at Reynolds number Re = 3900, generated by Direct Numerical "
        "Simulation (DNS) using Incompact3d."
    ),
    "paper": {
        "title": (
            "Lagrangian and Eulerian dataset of the wake downstream of a smooth "
            "cylinder at a Reynolds number equal to 3900"
        ),
        "authors": [
            "Ali Rahimi Khojasteh",
            "Sylvain Laizet",
            "Dominique Heitz",
            "Yang Yang",
        ],
        "journal": "Data in Brief",
        "year": 2021,
        "doi": "10.1016/j.dib.2021.107725",
        "url": "https://www.sciencedirect.com/science/article/pii/S2352340921010003",
    },
    "data_repository": {
        "name": "Recherche Data Gouv (Data INRAE)",
        "doi": "10.15454/GLNRHK",
        "url": "https://entrepot.recherche.data.gouv.fr/dataset.xhtml?persistentId=doi:10.15454/GLNRHK",
    },
    "github": "https://github.com/AliRKhojasteh/cylinder-wake-re3900",
    "license": "CC-BY-4.0",
    "physics": {
        "reynolds_number": 3900,
        "geometry": "smooth circular cylinder",
        "flow_type": "incompressible, turbulent wake",
        "solver": "Incompact3d (open-source DNS)",
        "scheme_temporal": "3rd-order Adams-Bashforth",
        "particle_transport": "4th-order Runge-Kutta",
        "scheme_spatial": "6th-order compact finite differences",
        "particle_interpolation": "trilinear",
    },
    "data_contents": {
        "eulerian_3d_subdomain_1": {
            "description": "Large near-wake region, 100 snapshots every 10 DNS steps",
            "fields": ["ux (U)", "uy (V)", "uz (W)"],
            "dimensions": "10D x 8D x 6D",
            "grid": {"nx": 768, "ny": 779, "nz": 256},
            "n_snapshots": 100,
            "dt": "0.0075 D/U_inf",
            "snapshot_size": "4.8 GB",
            "total_velocity_files": 24,
            "format_original": ".txt in .zip (4 chunks of 25 per component)",
            "format_ml": "HDF5 with gzip, shape (3, 768, 779, 256)",
        },
        "eulerian_3d_subdomain_2": {
            "description": "Small high-temporal-resolution region, 1000 snapshots every DNS step",
            "fields": ["ux (U)", "uy (V)", "uz (W)", "pressure (P)"],
            "dimensions": "4D x 2D x 2D",
            "grid": {"nx": 308, "ny": 328, "nz": 87},
            "n_snapshots": 1000,
            "dt": "0.00075 D/U_inf",
            "snapshot_size": "256 MB",
            "format_original": ".txt in .zip (2 chunks of 499/501 per component)",
            "format_ml": "HDF5 with gzip, shape (3, 308, 328, 87)",
            "note": "Pressure only available for Sub-domain 2",
        },
        "eulerian_2d": {
            "fields": ["ux", "uy"],
            "description": "Mid-plane velocity snapshots for both sub-domains",
            "format_original": ".txt in .zip",
            "format_ml": "HDF5",
        },
        "lagrangian": {
            "description": "Synthetic tracer particle trajectories (RK4 + trilinear interp.)",
            "n_particles": "~200,000 total (~100k per sub-domain)",
            "fields": ["x", "y", "z", "u", "v", "w"],
            "subdomains": ["Sub-domain 1 (near-wake)", "Sub-domain 2 (far-wake)"],
            "format_original": ".txt in .zip",
            "format_ml": "HDF5",
        },
        "grid": {
            "description": "Computational mesh (uniform in x,z; stretched in y near cylinder)",
            "format": ".txt",
            "finest_grid": "dy_min = 0.00563D (near cylinder center)",
        },
        "total_dataset_size": "~288 GB (24 zip files)",
    },
    "ml_benchmark_tasks": [
        {
            "name": "temporal_forecasting",
            "description": "Predict future Eulerian snapshots from past ones",
            "input": "Sequence of velocity fields at t, t-1, ..., t-k",
            "output": "Velocity field at t+1",
            "metric": "relative L2 error, SSIM",
        },
        {
            "name": "super_resolution",
            "description": "Reconstruct high-resolution fields from coarsened input",
            "input": "Downsampled velocity field (4x, 8x, 16x)",
            "output": "Full-resolution velocity field",
            "metric": "relative L2 error, spectral error",
        },
        {
            "name": "sparse_reconstruction",
            "description": (
                "Reconstruct full Eulerian field from sparse Lagrangian observations. "
                "Unique to this dataset: paired Lagrangian + Eulerian data."
            ),
            "input": "Sparse particle positions + velocities",
            "output": "Full 3D velocity + pressure field",
            "metric": "relative L2 error",
        },
        {
            "name": "lagrangian_prediction",
            "description": "Predict particle trajectories from Eulerian velocity field",
            "input": "Eulerian velocity field + initial particle positions",
            "output": "Particle positions at future time steps",
            "metric": "mean trajectory error",
        },
    ],
    "quick_start": {
        "install": "pip install cylinderwake3900",
        "python": [
            "from cylinderwake import CylinderWake3900",
            "",
            "# Load Eulerian data (auto-downloads on first use)",
            "ds = CylinderWake3900('eulerian', 'near', split='train')",
            "sample = ds[0]",
            "print(sample['velocity'].shape)  # (3, Nx, Ny, Nz)",
            "",
            "# Load Lagrangian data",
            "ds_lag = CylinderWake3900('lagrangian', 'near')",
            "sample = ds_lag[0]",
            "print(sample['positions'].shape)  # (N_particles, 3)",
        ],
        "cli": [
            "cylinderwake-download          # download raw data",
            "cylinderwake-convert           # convert to HDF5",
        ],
    },
    "citation_bibtex": """@article{khojasteh2021lagrangian,
  title     = {Lagrangian and {Eulerian} dataset of the wake downstream of a smooth cylinder at a {Reynolds} number equal to 3900},
  author    = {Khojasteh, Ali Rahimi and Laizet, Sylvain and Heitz, Dominique and Yang, Yang},
  journal   = {Data in Brief},
  volume    = {40},
  pages     = {107725},
  year      = {2021},
  publisher = {Elsevier},
  doi       = {10.1016/j.dib.2021.107725},
}""",
    "tags": [
        "fluid-mechanics", "CFD", "DNS", "turbulence", "cylinder-wake",
        "Lagrangian", "Eulerian", "particle-tracking", "PTV",
        "machine-learning", "benchmark", "physics-informed",
        "neural-operator", "PINN", "data-assimilation",
        "super-resolution", "forecasting", "Incompact3d",
        "Reynolds-3900", "open-data",
    ],
}


def get_dataset_card() -> dict:
    """Return the full dataset card as a Python dict."""
    return DATASET_CARD


def get_dataset_card_json() -> str:
    """Return the dataset card as a formatted JSON string."""
    import json
    return json.dumps(DATASET_CARD, indent=2, ensure_ascii=False)


def print_quick_start():
    """Print the quick-start guide to stdout."""
    qs = DATASET_CARD["quick_start"]
    print("=" * 60)
    print("  CylinderWake3900 — Quick Start")
    print("=" * 60)
    print(f"\n  Install:  {qs['install']}\n")
    print("  Python:")
    for line in qs["python"]:
        print(f"    {line}")
    print("\n  CLI:")
    for line in qs["cli"]:
        print(f"    {line}")
    print()
